// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaw4eX-CM59UzAmvSDh-wmQtpPmMQSLvA',
    appId: '1:977527880625:web:95fddd7fd091ce0a249b90',
    messagingSenderId: '977527880625',
    projectId: 'phoneauth-2eecf',
    authDomain: 'phoneauth-2eecf.firebaseapp.com',
    storageBucket: 'phoneauth-2eecf.appspot.com',
    measurementId: 'G-VC8QY4PXQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGeZgQe3QbsKkPYUxmwq2icxDtyv49VpE',
    appId: '1:977527880625:android:252e833b2c654098249b90',
    messagingSenderId: '977527880625',
    projectId: 'phoneauth-2eecf',
    storageBucket: 'phoneauth-2eecf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmfyI8c9MECdWwwKkqeDwCvCObNWPMEUo',
    appId: '1:977527880625:ios:bcf337927bee9f7a249b90',
    messagingSenderId: '977527880625',
    projectId: 'phoneauth-2eecf',
    storageBucket: 'phoneauth-2eecf.appspot.com',
    iosBundleId: 'com.example.phoneAuthUsingBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmfyI8c9MECdWwwKkqeDwCvCObNWPMEUo',
    appId: '1:977527880625:ios:bcf337927bee9f7a249b90',
    messagingSenderId: '977527880625',
    projectId: 'phoneauth-2eecf',
    storageBucket: 'phoneauth-2eecf.appspot.com',
    iosBundleId: 'com.example.phoneAuthUsingBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaw4eX-CM59UzAmvSDh-wmQtpPmMQSLvA',
    appId: '1:977527880625:web:1e547fc812fbacc4249b90',
    messagingSenderId: '977527880625',
    projectId: 'phoneauth-2eecf',
    authDomain: 'phoneauth-2eecf.firebaseapp.com',
    storageBucket: 'phoneauth-2eecf.appspot.com',
    measurementId: 'G-VGPL5CDNE1',
  );
}
